openapi: "3.0.0"
info:
paths:
  /operationAlpha:
    get:
      responses:
      requestBody:
        content:
          application/json:
            schema:
              type: "object"
              title: "operationAlphaRequest"
              properties:
                in:
                  type: "object"
                  title: "operationAlphaIn"
                  properties:
                    asset:
                      type: "object"
                      title: "operationAlphaInAsset"
                      properties:
                        id1:
                          type: "integer"
                          format: "int32"
                        id2:
                          type: "integer"
                          format: "int32"
  /operationBeta:
    get:
      responses:
      requestBody:
        content:
          application/json:
            schema:
              type: "object"
              title: "operationBetaRequest"
              properties:
                in:
                  type: "object"
                  title: "operationBetaIn"
                  properties:
                    asset:
                      type: "object"
                      title: "operationBetaInAsset"
                      properties:
                        id1:
                          type: "integer"
                          format: "int32"
                        id2:
                          type: "integer"
                          format: "int32"