version: '3.9'

services:

  webstudio:
    build:
      context: .
      args:
        "APP": STUDIO/org.openl.rules.webstudio/target/webapp
    container_name: webstudio
    ports:
      - "8181:8080"
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 384M
        reservations:
          memory: 32M

  ws:
    build:
      context: .
      args:
        "APP": WSFrontend/org.openl.rules.ruleservice.ws/target/webapp
    container_name: ws
    ports:
      - "8182:8080"
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 256M
        reservations:
          memory: 32M

  ws-all:
    build:
      context: .
      args:
        "APP": WSFrontend/org.openl.rules.ruleservice.ws.all/target/webapp
    container_name: ws-all
    ports:
      - "8183:8080"
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 256M
        reservations:
          memory: 32M

  demo:
    build:
      context: DEMO/org.openl.rules.demo
    container_name: demo
    ports:
      - "8184:8080"
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 640M
        reservations:
          memory: 32M
