version: '3.9'

services:

  webstudio:
    build:
      context: STUDIO/org.openl.rules.webstudio
      dockerfile: ../../Dockerfiles/WebApp
    container_name: webstudio
    ports:
      - "8181:8080"
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 384M
        reservations:
          cpus: '0.25'
          memory: 32M

  ws:
    build:
      context: WSFrontend/org.openl.rules.ruleservice.ws
      dockerfile: ../../Dockerfiles/WebApp
    container_name: ws
    ports:
      - "8182:8080"
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 256M
        reservations:
          cpus: '0.25'
          memory: 32M

  ws-all:
    build:
      context: WSFrontend/org.openl.rules.ruleservice.ws.all
      dockerfile: ../../Dockerfiles/WebApp
    container_name: ws-all
    ports:
      - "8183:8080"
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 256M
        reservations:
          cpus: '0.25'
          memory: 32M

  demo:
    build:
      context: DEMO/org.openl.rules.demo
    container_name: demo
    ports:
      - "8184:8080"
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 640M
        reservations:
          cpus: '0.25'
          memory: 32M
