version: '3.9'

services:

  webstudio:
    build:
      context: .
      args:
        "APP": STUDIO/org.openl.rules.webstudio/target/webapp
    container_name: webstudio
    ports:
      - "8181:8080"
      - "5501:5005" # Debug port
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 1024M
        reservations:
          memory: 512M
    environment:
        JAVA_OPTS: $JAVA_DEBUG_OPTS

  ws:
    build:
      context: .
      args:
        "APP": WSFrontend/org.openl.rules.ruleservice.ws/target/webapp
    container_name: ws
    ports:
      - "8182:8080"
      - "5502:5005" # Debug port
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 256M
        reservations:
          memory: 32M
    environment:
      JAVA_OPTS: $JAVA_DEBUG_OPTS

  ws-all:
    build:
      context: .
      args:
        "APP": WSFrontend/org.openl.rules.ruleservice.ws.all/target/webapp
    container_name: ws-all
    ports:
      - "8183:8080"
      - "5503:5005" # Debug port
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 256M
        reservations:
          memory: 32M
    environment:
      JAVA_OPTS: $JAVA_DEBUG_OPTS

  demo:
    build:
      context: DEMO
    container_name: demo
    ports:
      - "8184:8080"
      - "5504:5005" # Debug port
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 640M
        reservations:
          memory: 32M
    environment:
      JAVA_OPTS: $JAVA_DEBUG_OPTS
