# This workflow will build a Java project with Maven on the daily basis (aka Nightly Build).
# Checks all supported environments.
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Build

on:
  schedule:
    # Every day at 02:00 UTC
    - cron: '0 2 * * *'
  # Manual run from the GitHub action page
  workflow_dispatch:
    inputs:
      mavenArgs:
        description: 'Maven goals and parameters'
        required: false
        default: '-DnoPerf'
      branch:
        description: 'Branch to build'
        required: false
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        # test against latest update of each major Java version, as well as specific updates of LTS versions:
        java: [ 11, 17 ]
        os: [ ubuntu-latest, windows-latest, macOS-13 ]

    name: ${{ matrix.os }}/java-${{ matrix.java }}

    runs-on: ${{ matrix.os }}

    steps:

      # Docker is not installed on GitHub's MacOS hosted workers due to licensing issues
      # (and it's necessary to run testcontainers)
      - name: Setup docker and docker-compose (missing on MacOS)
        if: runner.os == 'macos'
        run: |
          echo "::group::brew install colima"
          brew install colima
          echo "::group::brew install docker docker-compose"
          brew install docker docker-compose
          echo "::group::colima start"
          # using mount-type 9p to allow the containers launched via docker-compose to chown
          # https://github.com/abiosoft/colima/issues/54#issuecomment-1250217077
          colima start --cpu 3 --memory 8 --disk 10  --mount-type 9p --network-address
          echo "::group::use colima"
          docker context use colima
          docker context ls
          echo "DOCKER_HOST=unix://${HOME}/.colima/default/docker.sock" >> $GITHUB_ENV
          echo "TESTCONTAINERS_DOCKER_SOCKET_OVERRIDE=/var/run/docker.sock" >> $GITHUB_ENV
          echo "TESTCONTAINERS_HOST_OVERRIDE=$(colima ls -j | jq -r '.address')" >> $GITHUB_ENV
          cat $GITHUB_ENV
          echo "::endgroup::"

        # Docker is not installed on GitHub's Widows hosted workers due to virtualization issues
        # (and it's necessary to run testcontainers)
      - name: Switch off dockerized tests on Windows
        if: runner.os == 'windows'
        run: |
          echo "SETTINGS=-DnoDocker" >> $env:GITHUB_ENV

      - name: Configure GIT
        run: |
          git config --global user.name "OpenL Tablets"
          git config --global user.email openltablets@gmail.com
          git config --global core.autocrlf false

      - name: Checkout ${{ github.event.inputs.branch }}
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.branch }}

      - name: Setup Java ${{ matrix.java }}
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.java }}
          cache: 'maven'

      - name: Maven version
        run: mvn -v

      - name: Build with Maven
        run: mvn "-Dstyle.color=always" ${{ env.SETTINGS }} ${{ github.event.inputs.mavenArgs }}
