# This workflow will build a Java project with Maven on the daily basis (aka Nightly Build).
# Checks all supported environments.
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Build

on:
  schedule:
  # Every day at 06:00 UTC
  - cron:  '0 6 * * *'
  # Manual run from the GitHub action page
  workflow_dispatch:
    inputs:
      mavenArgs:
        description: 'Maven parameters'
        required: true
        default: '-B verify --file pom.xml "-Dmaven.wagon.http.retryHandler.count=5"'

jobs:
  build:
    strategy:
      matrix:
        # test against latest update of each major Java version, as well as specific updates of LTS versions:
        java: [ 8, 11, 15 ]
        os: [ubuntu-latest, windows-latest, macOS-latest]

    runs-on: ${{ matrix.os }}
    name: ${{ matrix.os }}/java-${{ matrix.java }}

    steps:
    - uses: actions/checkout@v2
    - name: Setup Java ${{ matrix.java }}
      uses: actions/setup-java@v1
      with:
        java-version: ${{ matrix.java }}
    - name: Maven version
      run: mvn -v
    - name: Build with Maven
      run: mvn ${{ github.event.inputs.mavenArgs }}
