# This workflow will build a Java project with Maven on every push or pull request for quick checking of incoming commits.
# Verifies only on the latest Ubuntu LTS version and JDK 8.
# Checks performance on limited amount of memory to detect extra memory consumption by throwing timeouts and memory errors.
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Check

on:
  push:
    branches:
      - main
      - master
      - '5.*.x'
  pull_request:
  workflow_dispatch:

jobs:
  check:

    name: Quick Check

    runs-on: ubuntu-20.04

    steps:

    - name: Configure GIT
      run: |
        git config --global user.name "OpenL Tablets"
        git config --global user.email openltablets@gmail.com
        git config --global core.autocrlf false

    - uses: actions/checkout@v3

    - name: Setup Java 11
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: 11
        cache: 'maven'

    - name: Maven version
      run: mvn -v

    - name: Build with Maven
      run: mvn "-Dstyle.color=always"
