# This workflow will build a Java project with Maven on the daily basis (aka Nightly Build).
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Deploy Maven artifacts

on:
  schedule:
  # Every day at 23:00 UTC+3
  - cron:  '0 20 * * *'
  # Manual run from the GitHub action page
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to build'
        required: false

jobs:
  deploy:

    name: Deploy

    permissions:
      packages: write

    runs-on: ubuntu-latest

    steps:

    - name: Configure GIT
      run: |
        git config --global user.name "OpenL Tablets"
        git config --global user.email openltablets@gmail.com
        git config --global core.autocrlf false

    - name: Checkout ${{ github.event.inputs.branch }}
      uses: actions/checkout@v3
      with:
        ref: ${{ github.event.inputs.branch }}

    - uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: 8
        cache: 'maven'

    - name: Build with Maven
      run: mvn package -DskipTests "-Dstyle.color=always"

    - name: Deploy Maven artifacts
      run: |
        cd STUDIO/org.openl.rules.webstudio
        mvn deploy:deploy-file -DpomFile=pom.xml -Dfile=target/webstudio.war -Durl=https://maven.pkg.github.com/openl-tablets/openl-tablets -DrepositoryId=github
        cd ../../WSFrontend/org.openl.rules.ruleservice.ws
        mvn deploy:deploy-file -DpomFile=pom.xml -Dfile=target/webservice.war -Durl=https://maven.pkg.github.com/openl-tablets/openl-tablets -DrepositoryId=github
        cd ../../WSFrontend/org.openl.rules.ruleservice.ws.all
        mvn deploy:deploy-file -DpomFile=pom.xml -Dfile=target/webservice-all.war -Durl=https://maven.pkg.github.com/openl-tablets/openl-tablets -DrepositoryId=github
        cd ../../DEMO/org.openl.rules.demo
        mvn deploy:deploy-file -DpomFile=pom.xml -Dfile=target/openl-tablets-demo.zip -Dpackaging=zip -Durl=https://maven.pkg.github.com/openl-tablets/openl-tablets -DrepositoryId=github
      env:
        GITHUB_TOKEN: ${{ github.token }}

    - name: Build Docker images
      run: |
        repo=ghcr.io/${{ github.repository_owner }}
        cd Dockerfiles
        docker build -t $repo/ws:x        -f WebApp ../WSFrontend/org.openl.rules.ruleservice.ws
        docker build -t $repo/ws:x-all    -f WebApp ../WSFrontend/org.openl.rules.ruleservice.ws.all
        docker build -t $repo/webstudio:x -f WebApp ../STUDIO/org.openl.rules.webstudio
        docker build -t $repo/demo:x      -f Demo   ../DEMO/org.openl.rules.demo/target
        #
        echo ${{ github.token }} | docker login ghcr.io -u ${{ github.repository_owner }} --password-stdin
        docker push -a $repo/demo
        docker push -a $repo/ws
        docker push -a $repo/webstudio
