# This workflow will build a Java project with Maven on the daily basis (aka Nightly Build).
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Deploy Maven artifacts

on:
  schedule:
  # Every day at 06:00 UTC
  - cron:  '0 6 * * *'
  # Manual run from the GitHub action page
  workflow_dispatch:
    inputs:
      mavenArgs:
        description: 'Maven parameters'
        required: true
        default: '-B deploy --file pom.xml -Psources -DskipTests '
      java:
        description: 'Java version (8, 11)'
        required: true
        default: '8'

jobs:
  deploy:

    name: Deploy

    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v2

    - uses: actions/setup-java@v1
      with:
        java-version: ${{ github.event.inputs.java }}

    - name: Set environment variables
      run: |
        echo "WEEK=$(date +%U)" >> $GITHUB_ENV
        echo "DAY=$(date +%w)" >> $GITHUB_ENV
      shell: bash

    - name: Cache local Maven repository
      uses: actions/cache@v2
      with:
        path: ~/.m2/repository
        key: maven-x${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          maven-${{ env.WEEK }}-${{ env.DAY }}
          maven-${{ env.WEEK }}
          maven-

    - name: Maven version
      run: mvn -v

    - name: Build with Maven
      run: mvn ${{ github.event.inputs.mavenArgs }}
      env:
        GITHUB_TOKEN: ${{ github.token }}
