# This workflow will build a Java project with Maven on every push or pull request for quick checking of incoming commits.
# Verifies only on the latest Ubuntu LTS version and JDK 8.
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Check

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
    - name: Setup Java 8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Maven version
      run: mvn -v
    - name: Build with Maven
      run: mvn -B verify --file pom.xml -Dmaven.wagon.http.retryHandler.count=5
