name: Trivy

on:
  schedule:
    # Every day at 24:00 UTC+3
    - cron:  '0 21 * * *'
  # Manual run from the GitHub action page
  workflow_dispatch:
    inputs:
      registry:
        description: 'Docker registry'
        required: false
        default: 'openltablets'
      version:
        description: 'Image version'
        required: false
        default: 'latest'
jobs:
  trivy:
    strategy:
      fail-fast: false
      matrix:
        image: [ 'webstudio', 'ws', 'demo', 'ws-all' ]

    if: ${{ (matrix.image != 'ws-all') || (github.event.inputs.version != 'latest') }}

    runs-on: ubuntu-latest

    name: Trivy

    steps:

      - name: Setup defaults in environment variables
        run: |
          REGISTRY=${{ github.event.inputs.registry }}
          REGISTRY=${REGISTRY:ghcr.io/openl-tablets}
          NAME=${{ (matrix.image == 'ws-all' && 'ws') || matrix.image }}
          VERSION=${{ github.event.inputs.version }}
          VERSION=${VERSION:x}${{ (matrix.image == 'ws-all' && '-all') || '' }}
          VERSION=${{ (matrix.image == 'ws-all' && 'ws') || matrix.image }}
          echo "IMAGE_REF=${REGISTRY}/${NAME}:${VERSION}" >> $GITHUB_ENV

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: '${{ env.IMAGE_REF }}'
          format: 'table'
          exit-code: '1'
          #ignore-unfixed: true
          vuln-type: 'os,library'
          #severity: 'CRITICAL,HIGH'
